parameters:
    ResourceGroupName:
    AzureServiceConnection: 
    SubscriptionId: 
    Location:
    ParameterFile:

steps:    
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
              Write-Host $(armpath)
              write-host ${{ parameters.ParameterFile }}
              Get-ChildItem -Path $(armpath) -verbose
              
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create ServicePlans
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location: ${{ parameters.Location }}
    templateLocation: 'Linked artifact'
    csmFile: $(armpath)\servicePlans.json
    csmParametersFile: $(armpath)\${{ parameters.ParameterFile }}
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create WebApps
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location:  ${{ parameters.Location }}
    templateLocation: ${{ parameters.Location }}
    csmFile: '$(armpath)/webApps.json'
    csmParametersFile: '$(armpath)/${{ parameters.ParameterFile }}'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create Slots
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location:  ${{ parameters.Location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(armpath)/slots.json'
    csmParametersFile: '$(armpath)/${{ parameters.ParameterFile }}'
    deploymentMode: 'Incremental'