parameters:
    ResourceGroupName:
    AzureServiceConnection: 
    SubscriptionId: 
    Location:
    ParameterFile:

steps:    
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create ServicePlans
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location: ${{ parameters.Location }}
    templateLocation: 'Linked artifact'
    csmFile: './servicePlans.json'
    csmParametersFile: './${{ parameters.ParameterFile }}'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create WebApps
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location:  ${{ parameters.Location }}
    templateLocation: ${{ parameters.Location }}
    csmFile: '$(System.DefaultWorkingDirectory)/webApps.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/${{ parameters.ParameterFile }}'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create Slots
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: ${{ parameters.AzureServiceConnection }}
    subscriptionId: ${{ parameters.SubscriptionId }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.ResourceGroupName }}
    location:  ${{ parameters.Location }}
    templateLocation: 'Linked artifact'
    csmFile: '$(System.DefaultWorkingDirectory)/slots.json'
    csmParametersFile: '$(System.DefaultWorkingDirectory)/${{ parameters.ParameterFile }}'
    deploymentMode: 'Incremental'