trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create ServicePlan
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(4f8a172d-4607-4dbb-b7d7-427f169b13a1)'
    subscriptionId: '4f8a172d-4607-4dbb-b7d7-427f169b13a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Agent.BuildDirectory)/s/appPlans.json'
    csmParametersFile: '$(Agent.BuildDirectory)/s/$(int.param)'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create WebApps
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(4f8a172d-4607-4dbb-b7d7-427f169b13a1)'
    subscriptionId: '4f8a172d-4607-4dbb-b7d7-427f169b13a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Agent.BuildDirectory)/s/webApps.json'
    csmParametersFile: '$(Agent.BuildDirectory)/s/$(int.param)'
    deploymentMode: 'Incremental'

- task: AzureResourceManagerTemplateDeployment@3
  displayName: Create WebApps Slot
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Free Trial(4f8a172d-4607-4dbb-b7d7-427f169b13a1)'
    subscriptionId: '4f8a172d-4607-4dbb-b7d7-427f169b13a1'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'test'
    location: 'West Europe'
    templateLocation: 'Linked artifact'
    csmFile: '$(Agent.BuildDirectory)/s/webAppSlots.json'
    csmParametersFile: '$(Agent.BuildDirectory)/s/$(int.param)'
    deploymentMode: 'Incremental'

