jobs:
- template: Deploy.Base.yml
  parameters:
    EnvironmentName: 'TST'
    ResourceGroupName: 'test'
    AzureServiceConnection: 'RMS connection'
    SubscriptionId: '4f8a172d-4607-4dbb-b7d7-427f169b13a1'
    Location: 'West Europe'
    ParameterFile: '$(Build.SourcesDirectory)/ARM/Parameters/tst.parameters.json'
