parameters:
    EnvironmentName:
    ResourceGroupName:
    AzureServiceConnection: 
    SubscriptionId: 
    Location:
    ParameterFile:

jobs:
- deployment: Deploy_Headless
  displayName: 'Deploy Headless'
  pool:
    vmImage: 'ubuntu-latest'
  environment: ${{ parameters.EnvironmentName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: ../Jobs/deploy.headless.yml
          parameters:
            ResourceGroupName: ${{ parameters.ResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            Location: ${{ parameters.Location }}
            ParameterFile: ${{ parameters.ParameterFile }}